### ISSUE TITLE
train model with partial frozen filters on cuda

### ISSUE THREAD

**Issue by esoufleri** [galidor/PyTorchPartialLayerFreezing#2] opened 2021-05-19 17:52 UTC
Hi,

I am trying to freeze some filters of the conv2d layer and train the network on cuda. However, this gives error in the backward pass. Could you please help me with that ? 
The error is : 
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Thanks!

**Comment by galidor** [comment] 2021-05-26 15:55
Hey @esoufleri, thank you for reaching out with this issue. I will try to replicate it, and get back to you with a solution soon. :)

**Comment by galidor** [comment] 2021-05-26 16:23
Hey! I think I will need some of your code to reproduce the issue. As you can see, I added some CUDA tests to the test.py, and it worked quite fine, so I have to look closer at the code that causes the issue.

**Comment by esoufleri** [comment] 2021-06-09 07:25
Hi, 

Once I am using the standard pytorch training code, then the code runs on cuda. The issue was because I am trying to run this code for freezing filters in Spiking Neural Networks. Here is the repo that I am using : https://github.com/nitin-rathi/hybrid-snn-conversion  , for training vgg5 on cifar10. If you could have a look and tell me what modifications I should do, it would be very helpful!

Thanks!

**Comment by galidor** [comment] 2021-06-14 18:37
Sorry for the delay, I will try to have a look at it tomorrow. :)

**Comment by galidor** [comment] 2021-06-15 16:38
Hey @esoufleri, I just finished checking the repo you linked and I think I didn't came across any CUDA issues. The only bug I was able to find was lack of support for the bias=False layers, which is now fixed. From what I saw, the SNN code is quite memory-heavy as it needs roughly ~9-10 GB of VRAM on my machine to run. Are you sure you didn't move some tensors to CPU at some point so save the memory? Please contact me directly at mikolaj.jankowski17@imperial.ac.uk, and I will be happy to help you individually, as your issue is probably not caused by this repo.

**Closed as completed** 2021-06-15 16:42 UTC
